# Generated by Django 2.2.4 on 2019-08-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmLevels',
            fields=[
                ('id_level', models.AutoField(primary_key=True, serialize=False)),
                ('level_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'adm_levels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id_country', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id_field', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'fields',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OffCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'off_country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id_offer', models.AutoField(primary_key=True, serialize=False)),
                ('offer_name', models.CharField(max_length=200)),
                ('info', models.TextField()),
                ('link', models.TextField()),
                ('deadline', models.DateField()),
            ],
            options={
                'db_table': 'offers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OffField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'off_field',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OffLevl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'off_levl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OffType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'off_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'types',
                'managed': False,
            },
        ),
    ]
