# Generated by Django 2.2.4 on 2019-08-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fieldss',
            fields=[
                ('id_field', models.AutoField(primary_key=True, serialize=False)),
                ('fields_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'fields',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Fields',
        ),
    ]
